name: Build and Push Docker Image

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Build with Gradle
      run: ./gradlew build

    - name: Make distribution folder
      run: mkdir distribution

    - name: Untar dist
      run: tar -xf build/distributions/rest-service-0.0.1-SNAPSHOT.tar  -C distribution --strip-components=1

    - name: Login to Quay.io
      uses: docker/login-action@v1 
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Containerfile
        push: true
        tags: quay.io/jland/gradle-demo-cryostat:${{ github.ref_name }}

    - name: Build and push LATEST Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Containerfile
        push: true
        tags: quay.io/jland/gradle-demo-cryostat:latest

